-- ===============================================================
-- 1. MIGRATION: Add temp_child_data column to parent tables
-- ===============================================================
-- Run this for each parent table that needs atomic child saving.
-- Example for 'inspections':
-- ALTER TABLE inspections ADD COLUMN IF NOT EXISTS temp_child_data JSONB DEFAULT '{}'::jsonb;

-- ===============================================================
-- 2. TRIGGER FUNCTION: process_child_data_on_save
-- ===============================================================
CREATE OR REPLACE FUNCTION process_child_data_on_save()
RETURNS TRIGGER AS $$
DECLARE
    child_table TEXT;
    child_config JSONB;
    fk_col TEXT;
    records JSONB;
    record_item JSONB;
    pk_val TEXT;
    pk_col TEXT;
BEGIN
    -- Get the primary key column name from trigger arguments (default to 'id')
    pk_col := COALESCE(TG_ARGV[0], 'id');
    
    -- Extract PK value from the NEW record using JSON conversion for dynamic access
    pk_val := (to_jsonb(NEW) ->> pk_col);

    -- If PK is null, we can't link children. 
    -- This might happen on BEFORE INSERT if ID is generated by DB.
    -- In that case, the trigger should be AFTER INSERT.
    IF pk_val IS NULL THEN
        RETURN NEW;
    END IF;

    -- Check if temp_child_data is present and not empty
    IF NEW.temp_child_data IS NULL OR NEW.temp_child_data = '{}'::jsonb THEN
        RETURN NEW;
    END IF;

    -- Iterate through each child table in the JSON payload
    -- Expected Structure: 
    -- {
    --   "table_name": {
    --     "fk_column": "parent_id",
    --     "records": [{"field": "val"}, ...]
    --   }
    -- }
    FOR child_table, child_config IN SELECT * FROM jsonb_each(NEW.temp_child_data)
    LOOP
        fk_col := child_config ->> 'fk_column';
        records := child_config -> 'records';

        -- 1. Wipe existing records (Wipe & Replace strategy for Drafts/Updates)
        EXECUTE format('DELETE FROM %I WHERE %I = $1', child_table, fk_col) USING pk_val;

        -- 2. Insert new records
        IF records IS NOT NULL AND jsonb_array_length(records) > 0 THEN
            FOR record_item IN SELECT * FROM jsonb_array_elements(records)
            LOOP
                -- Inject the parent PK into the child record JSON
                record_item := record_item || jsonb_build_object(fk_col, pk_val);
                
                -- Dynamically populate the record and insert
                EXECUTE format(
                    'INSERT INTO %I SELECT * FROM jsonb_populate_record(NULL::%I, $1)',
                    child_table, child_table
                ) USING record_item;
            END LOOP;
        END IF;
    END LOOP;

    -- Clear the temp column to avoid storing redundant data in the parent row
    -- Note: This only works in BEFORE triggers. 
    -- If using AFTER triggers, the column remains as a log (which is often useful).
    -- NEW.temp_child_data := '{}'::jsonb; 

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ===============================================================
-- 3. HELPER: Function to attach trigger to a table
-- ===============================================================
CREATE OR REPLACE FUNCTION attach_child_sync_trigger(p_table_name TEXT, p_pk_col TEXT DEFAULT 'id')
RETURNS VOID AS $$
BEGIN
    -- Add the column if it doesn't exist
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS temp_child_data JSONB DEFAULT ''{}''::jsonb', p_table_name);

    -- Drop existing trigger if it exists
    EXECUTE format('DROP TRIGGER IF EXISTS trg_sync_children_%I ON %I', p_table_name, p_table_name);

    -- Create the trigger (AFTER is safer for generated IDs)
    EXECUTE format(
        'CREATE TRIGGER trg_sync_children_%I 
         AFTER INSERT OR UPDATE ON %I 
         FOR EACH ROW EXECUTE FUNCTION process_child_data_on_save(%L)',
        p_table_name, p_table_name, p_pk_col
    );
END;
$$ LANGUAGE plpgsql;

-- ===============================================================
-- 4. USAGE EXAMPLE (Run this for your tables)
-- ===============================================================
-- SELECT attach_child_sync_trigger('inspections', 'id');
-- SELECT attach_child_sync_trigger('my_custom_parent_table', 'ROWID');
